name: Python todo application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask openai requests
    - name: Run application
      run: |
        python app.py &
        sleep 20  # Give the application some time to start
        kill %1  # Stop the application
